#spring 配置
spring:
  #  mvc:
  #    throw-exception-if-no-handler-found: true
  #  resources:
  #    add-mappings: false
  jpa:
    #开启对resource下静态文件的访问
    open-in-view: true
  aop:
    proxy-target-class: true
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      datasource:
        master:
          username: root
          password: yingxing
          url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useAffectedRows=true
          driver-class-name: com.mysql.cj.jdbc.Driver
        slave:
          username: root
          password: yingxing
          url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useAffectedRows=true
          driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      resolve-lazily: false
  redis:
    database: 15
    host: localhost
    port: 6379
    password: ehuo
    jedis:
      pool:
        max-active: 50
        max-idle: 20
        max-wait: -1ms
        min-idle: 0


mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    lazyLoadingEnabled: false
    multipleResultSetsEnabled: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# server 配置
server:
  port: 8080
  servlet:
    context-path: /


#文件上传



